modLoader="javafml"
loaderVersion="[40,)"
license="MIT License"

[[mods]]
modId="dragon_pets"
version="1.0.0"
displayName="Dragon Pets"
credits="mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="beth"

[[dependencies.dragon_pets]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2]"
    ordering="NONE"
    side="BOTH"




